---
# tasks file for client-apple

- name: Build the mobileconfigs
  template:
    src: mobileconfig.j2
    dest: "{{ client_config_output_folder + item.0.name + '.mobileconfig' }}"
    mode: 0600
  become: no
  delegate_to: localhost
  with_together:
    - "{{ keymanager.result.clients }}"
    - "{{ keymanager.result.p12_passphrase }}"
  no_log: True